[package]
name = "dingo_test_runner"
version = "0.2.0"
edition = "2021"

[dependencies]
# MySQL 驱动
mysql = "25.0.1"

# SQLite 驱动 (用于本地调试)
rusqlite = { version = "0.31.0", features = ["bundled"] }

# CLI 解析
clap = { version = "4.5.4", features = ["derive"] }

# 日志
log = "0.4.21"
env_logger = "0.11.3"

# XML 生成
quick-xml = { version = "0.31", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde-xml-rs = "0.6"

# 并发
rayon = "1.7"
crossbeam = "0.8"

# 错误处理
anyhow = "1.0"
thiserror = "1.0"

# 字符串映射
phf = { version = "0.11.2", features = ["macros"] }

# 正则表达式
regex = "1.10.4"

# 时间处理
chrono = { version = "0.4", features = ["serde"] }

# 邮件 (暂时用于桩代码)
lettre = { version = "0.11", optional = true }

# 目录遍历
walkdir = "2.5.0"
once_cell = "1.21.3"

[features]
default = []
email = ["lettre"]

[dev-dependencies]
# ... existing code ...
