name: PR Check

on:
  pull_request:
    branches: [dev, master]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Quick Check
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        
      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          
      - name: Check compilation
        run: cargo check --all-targets --all-features 